export const SAMPLE_PROFILE_DATA = {
  username: "johndoe",
  profile: {
    fullName: "Alex Rivera",
    title: "Senior Product Designer & Web Developer",
    bio: "I design and build high-performance, accessible, and clean digital experiences. Currently crafting responsive products and interactive design systems at Acme Inc.",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400&h=400",
    location: "New York City, NY",
    email: "alex@riveradesign.co",
    resumeUrl: "https://example.com/resume.pdf",
  },
  skills: [
    "Product Design",
    "UI/UX Design",
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
    "Figma",
    "Framer Motion",
    "Web Accessibility (A11y)",
    "Node.js",
  ],
  projects: [
    {
      title: "PortfolioForge",
      description: "A gorgeous, no-code portfolio builder that lets developers and designers launch their hosted sites in under 5 minutes with interactive live previews.",
      techStack: ["Next.js", "TypeScript", "Tailwind CSS", "MongoDB", "Framer Motion"],
      liveUrl: "https://portfolioforge.com",
      githubUrl: "https://github.com/example/portfolioforge",
      imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600",
    },
    {
      title: "Vesper — AI Mood Music App",
      description: "An interactive mobile web application that uses device motion and environmental parameters to generate AI-curated soundscapes to boost productivity.",
      techStack: ["React", "Web Audio API", "Tailwind CSS", "Vercel"],
      liveUrl: "https://vesper.example.com",
      githubUrl: "https://github.com/example/vesper",
      imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=600",
    },
    {
      title: "Starlight Dashboard",
      description: "A dark-themed analytics console for tracking real-time server metrics, api requests, memory usage, and user growth across serverless deployments.",
      techStack: ["Next.js", "Recharts", "Radix UI", "WebSockets"],
      liveUrl: "https://starlight.example.com",
      githubUrl: "https://github.com/example/starlight",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    },
  ],
  experience: [
    {
      role: "Lead Product Designer",
      company: "Acme Inc.",
      from: "June 2022",
      to: "Present",
      description: "Leading the core product design team. Shipped over 12 features resulting in a 40% increase in user retention. Standardized the Figma design system.",
    },
    {
      role: "Frontend Engineer",
      company: "InnovateLabs",
      from: "Sept 2020",
      to: "May 2022",
      description: "Developed and maintained highly responsive React applications. Handled migration from legacy systems to Next.js, boosting SEO performance by 30%.",
    },
  ],
  education: [
    {
      school: "Georgia Institute of Technology",
      degree: "Bachelor of Science in Computer Science",
      from: "2016",
      to: "2020",
    },
  ],
  socials: {
    github: "https://github.com/example",
    linkedin: "https://linkedin.com/in/example",
    twitter: "https://twitter.com/example",
    website: "https://example.com",
  },
};
